### ISSUE TITLE
Preventing specialized consultants?

### ISSUE THREAD

**Issue by saibotsivad** [fossas/commons-clause#4]
The section defining "sell" raised a question:

> “Sell” means practicing any or all of the rights granted to you under the License to provide to third parties, for a fee or other consideration (including without limitation fees for hosting or consulting/ support services related to the Software), a product or service whose value derives, entirely or substantially, from the functionality of the Software.

The relevant section of that paragraph being the following:

> to provide to third parties, for a fee ... consulting/ support services related to the Software

That sounds like I couldn't offer consulting specializing in software that uses the Commons Clause.

For example, if this clause were applied to something like MySQL, I wouldn't be able to offer services like:

* Pay me X$ and I will install and configure a MySQL server.
* Pay me X$ and I will fix your broken MySQL server.
* Pay me X$ and I will consult you on what sort of MySQL server you need for your business.

Question: is preventing examples like I listed one of the goals of the Commons Clause?

I think the motivation for the Commons Clause in general is well explained, but it would be useful to expound a bit more on what the reasoning is in having the "consulting/support" clause. More details would be helpful in understanding motivation and intent for companies who want to use this license addendum.

**Comment by saibotsivad** [comment]
For a more at-hand example, Redis Labs is adding the Commons Clause to [certain modules](https://redislabs.com/community/licenses/), for example RedisSearch.

My interpretation of the "consulting/support" clause of the text would be that the use of the Commons Clause disallows a consultancy engineer offering services like:

* Pay me X$ and I will add and configure RedisSearch in your existing Redis server setup.
* Pay me X$ and I will consult you on whether you need the RedisSearch module and how you will want to configure it.

**Comment by heathermeeker** [comment]
Consulting would not be "a product or service whose value derives, entirely or substantially, from the functionality of the Software."  The value of consulting doesn't derive from what the software does ("functionality").

**Comment by saibotsivad** [comment]
So are you saying that the Commons Clause is *not* meant to prevent the examples I listed?

The structure of the sentence I quoted seems to tie "consulting/support" to the word "sell" in some way, and I'm not sure how else to interpret it other than forbidding the examples I listed.

Can you write a bit about what that parenthesis is trying to prevent? That would probably help me understand it better.

**Comment by xizhao** [comment]
@saibotsivad Yes, I believe so, as the value of consulting is additive, not "substantially" the same value.

If this is a major area of confusion for people, we can clarify this in the FAQ.

**Comment by heathermeeker** [comment]
Bear with a legal technicality, but the Commons Clause is not a restriction on performing services -- it can't be.  The license grant for the software is in the underlying license, and the Commons Clause claws back one kind of commercial use right.  So, picture the original grant as a Venn diagram circle, and the excluded right to Sell as a little circle inside that.  Providing services was not in the big circle in the first place, so the small circle can't change it.  

But perhaps you are thinking, can I use the software in order to provide my services?   That's a reasonable question.  In other words, is the right to use the software in support of professional services -- like development, maintenance, or analysis, clawed back by the exclusion?  No, because that use is not a service that derives its value from the functionality of the software.  Your professional services derive their value from your expertise, not what the software does.  The exclusion has to cover services, though, or it would have a big loophole.  Offering the software via SaaS as a substitute for distributing it, and selling that access, is the main kind of service that is meant to be limited.  Your consulting is not an economic substitute for the software.  SaaS is.

Of course, I'm not your lawyer, so technically I can't give you advice.  The clause means what it means, and although I led the drafting of the clause, that doesn't mean I have  authority to interpret documents.  That's not how the law works -- in the end, only a court has that power, no matter who wrote the document.  But I hope to be helpful and dispel any confusion.

**Comment by xizhao** [comment]
@heathermeeker, I suggest we can add a quick clarification in the FAQ and link to this Github Issue as I've seen this pop up before on HN and Twitter.

**Comment by mpdehaan** [comment]
I've shared on twitter, but here's some long-form comments on why I think this is a good idea to *start* here, but the terms about "substantial value" may possibly block people that, for instance, are using a product as a key internal component but are not reselling.

I think the language to describe what reselling to third parties is should be more explicit.

For instance, making a hosted-RDS type solution of a database is reselling, but using that database inside your .com petstore isn't.

As such I can't use this *NOW*, but want to use something like this.  Definitely up for a larger conversation.  Anyway, see blog post:

https://medium.com/@michaeldehaan/why-open-source-needs-new-licenses-d2d9d819a10

**Comment by mpdehaan** [comment]
Further clarification is I don't really want to *block* consulting either, consultants are great for patches and spreading software sometime, but I would like to encourage them (in my case) to buy a commercial license.  They are making money off the thing, so they should be able to share some of the funds from that thing.

**Comment by Lmpessoa** [comment]
I'm also considering switching from a regular open source license to Commons Clause but I also don't like the inclusion of "consulting/support" in this restriction. As well as @mpdehaan I would like to encourage people to use my software even to offer consulting/support services and (one I haven't seen explicitly covered here) educational courses. I believe these encourage people to use the software and even work as advertising for it. What we should be wary of is selling the software itself.

Thus, it is my opinion only, of course, that a license in these terms should restrict only the "right" to sell/rent the software itself, derivative works (from using the provided source code) or other services or applications embedding the software subject to the license and thus exclude completely the restriction to offer support/consulting services in any way.

I believe we need new "open-source" licenses that may help sustain this development model and this is a great initiative but I also believe it needs more discussing. After this, I may think of drafting my own "open-source except for sale" license and see how it goes but always keeping an eye here.

**Comment by saibotsivad** [comment]
@heathermeeker says:

> Your professional services derive their value from your expertise, not what the software does.

But if consulting/support is excluded because of the phrase "from the functionality of the Software" then why even have "consulting/support" in the CC at all? Doesn't it just add confusion?

For me, as a software consultant, offering consultancy specializing in software that uses the CC is a risk because 1) the general reading implies that some sort of limitation on consultancy exists, and 2) trying to get an answer on interpretation through a court cost is crazy expensive.

The only interpretation I have been able to make is that the intended desire of the Commons Clause is to *prevent* consulting/support services specific to the Software, e.g. the examples I listed originally.

Maybe that's my failure to understand English legalese, but if that's not the intent I would love to hear more about what the intent of the "consulting/support" phrase actually _is_, instead of what it _is not_.

**Comment by mpdehaan** [comment]
Here's the approach that I personally arrived at (trademarks, not copyright).  Thanks to Adam Jacob from Chef for being a good sounding board:

https://gist.github.com/mpdehaan/6c1bf2314ce89cac961b31da36c60252

While I like the idea of authors and communities having more control, it is clear there are some that are religiously opposed to new licenses, and that *does* suck.  However I sympathetize with legal departments who have preapproved license lists and can see that being an adoption barrier.

So I'm stuck between what I feel is right and smart vs what might not cause a lot of blowback. 

This is possibly a good middle ground.

**Comment by Lmpessoa** [comment]
@mpdehaan I liked this approach. Instead of preventing a person from offering consulting/supporting services, you prevent them from using the trademark so they can barely advertise they do unless they support the project and offer to list those supporting in order to even help them be found by those who need. Very clever!

However, this approach seems only to cover consulting/supporting and not derivative works made using your code. You mention they are on their own and have to rebrand the app but they are still able to sell the resulting software commercially either directly or embedded as another product or service and you are still maintaining their source of revenue without getting a dime for. That's what I wanted to avoid using CC.

As I said, I like your approach and I'd like to follow it but I wanted to have it structured in the form of a new generic open-source license anyone could adopt. I'm thinking about pausing my project to work on this.

**Comment by kortschak** [comment]
This has been closed, but the question above "Maybe that's my failure to understand English legalese, but if that's not the intent I would love to hear more [about](https://github.com/fossas/commons-clause/issues/4#issuecomment-416452295) what the intent of the "consulting/support" phrase actually _is_, instead of what it _is not_." has not been answered. That would go a long way towards clarifying this concerns here.

**Comment by miraculixx** [comment]
I came here from the link provided in the FAQ at https://commonsclause.com. I was specifically trying to understand what the Commons Clause means in relation to the very type of services asked in this thread. Unfortunatley this thread does not do anything to clarify, nor does the FAQ. All they do is confirm that there is an issue, but no resolve.

I am guessing that the author of the license wanted to add a provision against "smart" vendors who might claim to host the software for free but then charge for support/consulting instead, effectively just mincing words. This kind is however already 

On the other hand, the reference to consulting/support services in the clause is the source of confusion and does nothing to provide better protection against such providers - they could always claim that their consulting/support services add substantial value over the functionality of the Software itself and thus is not affected by the clause anyway. Also "product or service" already covers the case of a service (including support services) that is merely circumventing "hosting".

As a constructive proposal I suggest the remove the consulting/support services part from the Commons Clause as follows (IANAL):

_For purposes of the foregoing, “Sell” means practicing any or all of the rights granted to you under the License to provide to third parties, for a fee or other consideration (including without limitation fees for hosting Software), a product or service whose value derives, entirely or substantially, from the functionality of the Software. Any license notice or attribution required by the License must also include this Commons Cause License Condition notice._

Effectively this change would allow those providing consulting/support to continue to offer services as described by the original question, without taking away from the original intent.
